# -*- coding: utf-8 -*-
"""Tratamentos de erros

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/199GJJDkc7n9mctyB5qzOv5aSDBAgWM9J

# Erro e Exceções

Sempre leia mensagens de erro. Erros fazem parte do processo de aprendizado e vão acompanhar você na sua jornada em programação, em qualquer linguagem.
"""

# Erro  (leia a mensagem de erro)
print('hello)

# Erro (leia a mensagem de erro)
8+'s'

# Criando uma função
def numDiv (num1, num2):
  resultado = num1/num2
  print(resultado)

# Execução não gera erro
numDiv(4,2)

#Execução gerando erro (leia a mensagem de erro)
numDiv(4,0)

try:
  numDiv(4,0)
except ZeroDivisionError:
  print('Esta operação não pode ser divida por zero.')

"""# Try, Except,Finally"""

8 + 's'

try:
  8 + 's'
except TypeError:
  print('Operação não pode somar letras e números')

from os import write
# Utilizando try, except e else

try:
  f = open('arquivos/testandoerros.txt','w')
  f.write('escrevendo o arquivo')
except IOError:
  print('Erro: arquivo não encontrado ou não pode ser salvo.')
else:
  print('Conteudo gravado com sucesso!')
  f.close()

from os import write
# utilizando Try, except, else e  finally
try:
  f = open('arquivos/testandoerros.txt','r')
  f.write('escrevendo o arquivo')
except IOError:
  print('Erro: arquivo não encontrado ou não pode ser salvo.')
else:
  print('Conteudo gravado com sucesso!')
  f.close()
# Finally sempre vai execultar independente se der erro ou não no nosso programa.
finally:
  print('Comando no bloco finally são sempre executados.')

def askint():
  try:
    val = int(input('Digite um numero: '))
  except:
    print('Você não digitou um número!')
  finally:
    print('Obrigado	por usar nosso programa!')

askint()

def askint():
  try:
    val = int(input('Digite um numero: '))
  except:
    print('Você não digitou um número!')
    val = int(input('Digite um numero: '))
  finally:
    print('Obrigado	por usar nosso programa!')

askint()

def askint():
  while True:
    try:
      val = int(input('Digite um numero: '))
    except:
      print('Você não digitou um número!')
      continue
    else:
      print(f'Informação digitada: {val}')
      break
    finally:
      print('Obrigado	por usar nosso programa!')

askint()